### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by summersonne** [tainguyenbp/asterisk_exporter#1]
Trying to run your code and got:

curl localhost:9200
curl: (52) Empty reply from server

Looks like it doesn't returns anything

**Comment by summersonne** [comment]
Sorry, it's me being stupid.

It needs to be :9200/metrics

**Comment by t2ju9ny3u** [comment]
> Sorry, it's me being stupid.
> 
> It needs to be :9200/metrics

Sorry, I did not write docs in the readme.md file
